// ═══════════════════════════════════════════════════════════════════════
// Export utilities — CSV + PDF
// ───────────────────────────────────────────────────────────────────────
// Audit-finding fix (May 2026): exports were missing from Audit Logs,
// Onboarding pipeline, Finance commissions, and the Deals pipeline. This
// module provides a single pair of helpers used by all four surfaces.
//
//   exportCsv(filename, rows, columns)
//   exportPdf(filename, rows, columns, options)
//
// `columns` is an array of { key, label, format? } descriptors.
// ═══════════════════════════════════════════════════════════════════════

const csvEscape = (val) => {
  if (val === null || val === undefined) return '';
  const s = String(val);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
};

export const exportCsv = (filename, rows, columns) => {
  const header = columns.map(c => csvEscape(c.label)).join(',');
  const body = rows.map(row =>
    columns.map(c => {
      const raw = typeof c.key === 'function' ? c.key(row) : row[c.key];
      const val = c.format ? c.format(raw, row) : raw;
      return csvEscape(val);
    }).join(',')
  ).join('\n');
  const csv = `${header}\n${body}`;
  const blob = new Blob([`﻿${csv}`], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

// Build a printable HTML document and open it in a new window with the print
// dialog primed. Re-uses the pattern from the executive board pack PDF.
export const exportPdf = (filename, rows, columns, options = {}) => {
  const { title = filename, subtitle = '', brand = '#E8672A' } = options;
  const safe = (v) => String(v == null ? '' : v).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const head = columns.map(c => `<th>${safe(c.label)}</th>`).join('');
  const body = rows.map(row =>
    `<tr>${columns.map(c => {
      const raw = typeof c.key === 'function' ? c.key(row) : row[c.key];
      const val = c.format ? c.format(raw, row) : raw;
      return `<td>${safe(val)}</td>`;
    }).join('')}</tr>`
  ).join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${safe(title)}</title>
<style>
  @page { size: A4 landscape; margin: 14mm 12mm 14mm 12mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; margin: 0; padding: 0; }
  .hdr { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid ${brand}; padding: 0 0 10px; margin-bottom: 14px; }
  .hdr h1 { font-size: 18px; font-weight: 800; margin: 0; color: #0f172a; }
  .hdr .meta { font-size: 11px; color: #475569; text-align: right; }
  .hdr .meta b { color: ${brand}; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { background: ${brand}; color: #fff; text-align: left; padding: 6px 8px; font-weight: 700; }
  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) td { background: #f8fafc; }
  .footer { margin-top: 18px; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { .no-print { display: none; } }
</style></head>
<body>
  <div class="hdr">
    <div>
      <h1>${safe(title)}</h1>
      ${subtitle ? `<div style="font-size:11px;color:#64748b;margin-top:4px">${safe(subtitle)}</div>` : ''}
    </div>
    <div class="meta">
      <div><b>Homes Brokerage OS</b></div>
      <div>${new Date().toLocaleString('en-EG', { dateStyle: 'medium', timeStyle: 'short' })}</div>
      <div>${rows.length} record${rows.length === 1 ? '' : 's'}</div>
    </div>
  </div>
  <table>
    <thead><tr>${head}</tr></thead>
    <tbody>${body}</tbody>
  </table>
  <div class="footer">
    <span>Generated by Homes Brokerage OS · ${filename}.pdf</span>
    <span>Page <span class="pn"></span></span>
  </div>
  <script>setTimeout(() => { window.print(); }, 200);</script>
</body></html>`;

  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) {
    // Popup blocked — fall back to data URL
    const url = `data:text/html;charset=utf-8,${encodeURIComponent(html)}`;
    window.location.href = url;
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
};
