import React from 'react';
import { Eye, Pencil } from 'lucide-react';

const MasterTable = ({ title, subtitle, breadcrumb, columns, data, addLabel }) => (
  <div>
    <div className="page-header"><div className="page-breadcrumb"><span>Dashboard</span><span>&gt;</span><span>Master Data</span><span>&gt;</span><span className="current">{breadcrumb}</span></div><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div>
    <div className="data-panel"><div className="data-toolbar"><div className="data-toolbar-left"><input className="data-search" placeholder={`Search ${title.toLowerCase()}...`} /></div><button className="btn btn-primary">+ {addLabel||`Add ${breadcrumb}`}</button></div>
    <div className="data-scroll"><table className="data-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}<th style={{textAlign:'right'}}>Actions</th></tr></thead>
    <tbody>{data.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className={j===0?'muted':j===1?'bold':''}>{cell}</td>)}<td><div className="action-icons" style={{justifyContent:'flex-end'}}><span className="action-icon"><Eye size={16}/></span><span className="action-icon"><Pencil size={16}/></span></div></td></tr>)}</tbody></table></div></div>
  </div>
);

export const Developers = () => <MasterTable title="Developers" subtitle="Manage developer partners — Property" breadcrumb="Developers" addLabel="Add Developer" columns={['#','Name','Country','Projects','Status']}
  data={[['1','Palm Hills','Egypt','12',<span className="badge badge-success">Active</span>],['2','Ora Developers','Egypt','8',<span className="badge badge-success">Active</span>],['3','SODIC','Egypt','6',<span className="badge badge-success">Active</span>],['4','Mountain View','Egypt','10',<span className="badge badge-success">Active</span>],['5','Hyde Park','Egypt','4',<span className="badge badge-success">Active</span>],['6','Talaat Moustafa','Egypt','15',<span className="badge badge-success">Active</span>],['7','City Edge','Egypt','5',<span className="badge badge-success">Active</span>],['8','Better Home','Egypt','3',<span className="badge badge-warning">Pending</span>]]}/>;

export const MasterProjects = () => <MasterTable title="Projects" subtitle="Manage project inventory — Property" breadcrumb="Projects" addLabel="Add Project" columns={['#','Project','Developer','Location','Units','Status']}
  data={[['1','Palm Hills New Cairo','Palm Hills','New Cairo','450',<span className="badge badge-success">Published</span>],['2','ZED East','Ora Developers','New Cairo','680',<span className="badge badge-success">Published</span>],['3','Hacienda Bay','Palm Hills','North Coast','320',<span className="badge badge-success">Published</span>],['4','Madinaty','Talaat Moustafa','New Cairo','1200',<span className="badge badge-success">Published</span>],['5','Hyde Park','Hyde Park','New Cairo','580',<span className="badge badge-success">Published</span>],['6','Sodic West','SODIC','Sheikh Zayed','290',<span className="badge badge-gray">Draft</span>]]}/>;

export const Compounds = () => <MasterTable title="Compounds" subtitle="Manage compound groupings — Property" breadcrumb="Compounds" addLabel="Add Compound" columns={['#','Compound','Developer','City','Projects','Status']}
  data={[['1','New Cairo Compounds','Multiple','New Cairo','8',<span className="badge badge-success">Active</span>],['2','North Coast Resorts','Multiple','North Coast','5',<span className="badge badge-success">Active</span>],['3','6th October Zone','Multiple','6th October','4',<span className="badge badge-success">Active</span>],['4','Sheikh Zayed','Multiple','Sheikh Zayed','3',<span className="badge badge-success">Active</span>]]}/>;

export const UnitTypes = () => <MasterTable title="Unit Types" subtitle="Manage unit type classifications — Property" breadcrumb="Unit Types" addLabel="Add Unit Type" columns={['#','Type','Category','Status']}
  data={[['1','Apartment','Residential',<span className="badge badge-success">Active</span>],['2','Villa','Residential',<span className="badge badge-success">Active</span>],['3','Townhouse','Residential',<span className="badge badge-success">Active</span>],['4','Duplex','Residential',<span className="badge badge-success">Active</span>],['5','Penthouse','Residential',<span className="badge badge-success">Active</span>],['6','Chalet','Resort',<span className="badge badge-success">Active</span>],['7','Twin House','Residential',<span className="badge badge-success">Active</span>],['8','Studio','Residential',<span className="badge badge-success">Active</span>]]}/>;

export const Cities = () => <MasterTable title="Cities" subtitle="Manage city locations — Location" breadcrumb="Cities" addLabel="Add City" columns={['#','City','Region','Areas','Status']}
  data={[['1','Cairo','Greater Cairo','15',<span className="badge badge-success">Active</span>],['2','Giza','Greater Cairo','8',<span className="badge badge-success">Active</span>],['3','Alexandria','North Coast','6',<span className="badge badge-success">Active</span>],['4','North Coast','Coastal','12',<span className="badge badge-success">Active</span>],['5','Ain Sokhna','Red Sea','4',<span className="badge badge-success">Active</span>]]}/>;

export const AreasDistricts = () => <MasterTable title="Areas / Districts" subtitle="Manage area subdivisions — Location" breadcrumb="Areas / Districts" addLabel="Add Area" columns={['#','Area','City','Projects','Status']}
  data={[['1','New Cairo','Cairo','12',<span className="badge badge-success">Active</span>],['2','6th October','Giza','8',<span className="badge badge-success">Active</span>],['3','Sheikh Zayed','Giza','6',<span className="badge badge-success">Active</span>],['4','Heliopolis','Cairo','3',<span className="badge badge-success">Active</span>],['5','Maadi','Cairo','2',<span className="badge badge-success">Active</span>],['6','Sahel','North Coast','10',<span className="badge badge-success">Active</span>]]}/>;

export const Branches = () => <MasterTable title="Branches" subtitle="Manage office branches — Organization" breadcrumb="Branches" addLabel="Add Branch" columns={['#','Branch','City','Manager','Staff','Status']}
  data={[['1','New Cairo HQ','New Cairo','Nour El-Din','18',<span className="badge badge-success">Active</span>],['2','6th October','6th October','Omar Sherif','8',<span className="badge badge-success">Active</span>],['3','Sheikh Zayed','Sheikh Zayed','Mohamed Ali','6',<span className="badge badge-success">Active</span>],['4','Heliopolis','Heliopolis','—','0',<span className="badge badge-warning">Planned</span>]]}/>;

export const Teams = () => <MasterTable title="Teams" subtitle="Manage sales teams — Organization" breadcrumb="Teams" addLabel="Add Team" columns={['#','Team','Department','Leader','Members','Status']}
  data={[['1','Alpha','Sales','Karim Mostafa','5',<span className="badge badge-success">Active</span>],['2','Beta','Sales','Omar Sherif','4',<span className="badge badge-success">Active</span>],['3','Gamma','Sales','Mohamed Ali','3',<span className="badge badge-success">Active</span>]]}/>;

export const EmploymentCategories = () => <MasterTable title="Employment Categories" subtitle="Manage employment classifications — Organization" breadcrumb="Employment Categories" addLabel="Add Category" columns={['#','Category','Description','Status']}
  data={[['1','Licensed Agent','Full licensed real estate agent',<span className="badge badge-success">Active</span>],['2','Trainee Agent','Agent in training period',<span className="badge badge-success">Active</span>],['3','Team Leader','Sales team leadership role',<span className="badge badge-success">Active</span>],['4','Sales Manager','Senior sales management',<span className="badge badge-success">Active</span>],['5','Backoffice Staff','Administrative and operations',<span className="badge badge-success">Active</span>]]}/>;

export const MasterCommPolicies = () => <MasterTable title="Commission Policies" subtitle="Manage commission rate policies — Finance & Sales" breadcrumb="Commission Policies" addLabel="Add Policy" columns={['#','Developer','Project','Rate','Override','Status']}
  data={[['1','Palm Hills','Palm Hills New Cairo','2.0%','No',<span className="badge badge-success">Active</span>],['2','Ora','ZED East','2.0%','No',<span className="badge badge-success">Active</span>],['3','Hyde Park','Hyde Park NC','1.8%','No',<span className="badge badge-success">Active</span>],['4','Palm Hills','Hacienda Bay','2.2%',<span className="badge badge-warning">Yes</span>,<span className="badge badge-success">Active</span>],['5','TMG','Madinaty','1.5%','No',<span className="badge badge-success">Active</span>]]}/>;

export const PayoutCycles = () => <MasterTable title="Payout Cycles" subtitle="Manage payout schedule cycles — Finance & Sales" breadcrumb="Payout Cycles" addLabel="Add Cycle" columns={['#','Cycle','Frequency','Next Date','Status']}
  data={[['1','Monthly Agent Payout','Monthly','2024-02-01',<span className="badge badge-success">Active</span>],['2','Quarterly TL Bonus','Quarterly','2024-04-01',<span className="badge badge-success">Active</span>],['3','Annual Performance','Annually','2025-01-01',<span className="badge badge-gray">Scheduled</span>]]}/>;

export const ExpenseCategories = () => <MasterTable title="Expense Categories" subtitle="Manage expense classifications — Finance & Sales" breadcrumb="Expense Categories" addLabel="Add Category" columns={['#','Category','Type','Budget','Status']}
  data={[['1','Office Rent','Fixed','EGP 45,000/mo',<span className="badge badge-success">Active</span>],['2','Marketing','Variable','EGP 80,000/mo',<span className="badge badge-success">Active</span>],['3','Staff Salaries','Fixed','EGP 127,000/mo',<span className="badge badge-success">Active</span>],['4','Utilities','Fixed','EGP 8,000/mo',<span className="badge badge-success">Active</span>],['5','Training','Variable','EGP 15,000/mo',<span className="badge badge-success">Active</span>]]}/>;

export const LeadSources = () => <MasterTable title="Lead Sources" subtitle="Manage lead sources — Other" breadcrumb="Lead Sources" addLabel="Add Lead Source" columns={['#','Name','Actions']}
  data={[['1','Website'],['2','Social Media'],['3','Referral'],['4','Walk-in'],['5','Developer Event'],['6','Cold Call'],['7','Property Fair'],['8','Campaign'],['9','Marketplace']]}/>;
